let startActivityList=[
  {
    id:"1",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  },
  {
    id:"1",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  },
  {
    id:"2",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  }
]
let endActivityList=[
  {
    id:"1",
    title:"春节吃饺子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  },
  {
    id:"1",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  },
  {
    id:"1",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  }
]
let readyActivityList=[
  {
    id:"1",
    title:"中秋节午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  },
  {
    id:"1",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  },
  {
    id:"1",
    title:"端午节吃粽子大赛",
    imgSrc:"/images/test/1.png",
    desc:"迎接端午节抢粽子",
    initiator:"港式卤肉饭",
    startTime:"2020/10/23",
    endTime:"2020/10/25"
  }
]
module.exports={startActivityList,endActivityList,readyActivityList}