let blogList=[
    {
        author:{
            "img":"/images/avatar/3.png",
            "username":"jack"
        },
        img:"/images/test/2.png",
        id:1,
        publish:"2019/12/23",
        content:"contenntsdsdfsasdfasdffdsafadsfadsfadsfadsfasdfasdfsadfa",
        love_count:"234",
        attention_count:"34"
    },
    {
        author:{
            "img":"/images/avatar/3.png",
            "username":"jack"
        },
        img:"/images/test/2.png",
        id:1,
        publish:"2019/12/23",
        content:"contenntsdsdfsasdfasdffdsafadsfadsfadsfadsfasdfasdfsadfa",
        love_count:"234",
        attention_count:"34"
    },
    {
        author:{
            "img":"/images/avatar/2.png",
            "username":"jack"
        },
        img:"/images/test/2.png",
        id:1,
        publish:"2019/12/23",
        content:"contenntsdsdfsasdfasdffdsafadsfadsfadsfadsfasdfasdfsadfa",
        love_count:"234",
        attention_count:"34"
    },
    {
        author:{
            "img":"/images/avatar/1.png",
            "username":"jack"
        },
        img:"/images/test/2.png",
        id:1,
        publish:"2019/12/23",
        content:"contenntsdsdfsasdfasdffdsafadsfadsfadsfadsfasdfasdfsadfa",
        love_count:"234",
        attention_count:"34"
    }
]
module.exports={blogList}