let review={
    'id':1,
    'avatar':'/images/avatar/1.png',
    'author':'星眸大',
    'date':'2020/3/3',
    'content':'hlejflkadjflkjalkdfjalk'
}
let childReviews=[
    {
        'id':1,
        'avatar':'/images/avatar/5.png',
        'author':'dgy',
        'date':'2021/3/1',
        'content':'fdsfjladslkfja'
    },
    {
        'id':2,
        'avatar':'/images/avatar/3.png',
        'author':'dgy',
        'date':'2021/3/1',
        'content':'fdsfjladslkfja'
    },
    {
        'id':3,
        'avatar':'/images/avatar/1.png',
        'author':'dgy',
        'date':'2021/3/1',
        'content':'fdsfjladslkfja'
    },
    {
        'id':4,
        'avatar':'/images/avatar/2.png',
        'author':'dgy',
        'date':'2021/3/1',
        'content':'fdsfjladslkfja'
    }
]
module.exports={review,childReviews}