let shopInfo={
  collectedNum:24,
  id:"1",
  desc:"主营米饭套餐香辣口味",
  name:"湖南大碗菜",
  location:"新食堂一楼",
  view:'1000',
  rate:'8.3', 
  todayMenu:[{
    imgSrc:"/images/test/1.png",
    id:0,
    name  :"烧鹅"
  },{
    imgSrc:"/images/test/1.png",
    id:1,
    name:"农家小炒肉"
  }],
  menu:[
    {
      imgSrc:"/images/test/1.png",
      id:0,
      name:"农家小炒肉"
    },
    {
      imgSrc:"/images/test/1.png",
      id:1,
      name:"腊肉"
    },  
    {
      imgSrc:"/images/test/1.png",
      id:1,
      name:"红烧肉"
    },
    {
      imgSrc:"/images/test/2.png",
      id:1,
      name:"猪手"
    }
  ],
  recommendMenu:[
    {
      id:1,
      imgSrc:"/images/test/2.png",
      name:"猪脚"
    },
    {
      id:0,
      imgSrc:"/images/test/2.png",
      name:"红烧肉"
    },
    {
      id:1,
      imgSrc:"/images/test/1.png",
      name:"香肠"
    },
    {
      id:0,
      imgSrc:"/images/test/1.png",
      name:"卤肉饭"
    }
  ],
  images:[
    {
      img:"/images/test/2.png"  
    },{
      img:"/images/test/2.png"  
    },
  ]
}
module.exports = {shopInfo}